export enum BadgeType {
    EMPTY_BADGE = 'EMPTY_BADGE',
    FAIL_BADGE = 'FAIL_BADGE',
    SUCCESS_BADGE = 'SUCCESS_BADGE',
    NAVIGATION_BADGE = 'NAVIGATION_BADGE',
    SHELTER_BADGE = 'SHELTER_BADGE',
    WILDLIFE_BADGE = 'WILDLIFE_BADGE',
    NULL = ''
}
